hello/app1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("ycy", views.ycy, name="ycy"),
    path("<str:name>", views.greet, name="greet")
]

hello/hello/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include("app1.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
    path('', views.index, name='index')
]

hello/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

hello/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name='index'),
    path("add", views.add, name="add")
]

hello/app1/models.py
from django.db import models

# Create your models here.

hello/newyear/models.py
from django.db import models

# Create your models here.

hello/tasks/models.py
from django.db import models

# Create your models here.

hello/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "app1/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def ycy(request):
    return HttpResponse("Hello, ycy!")

def greet(request, name):
    return render(request, "app1/greet.html", {
        "name": name.capitalize()
    })

hello/hello/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    
    return render(request, "hello/index.html")

hello/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

hello/tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form 
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

hello/app1/templates/app1/greet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Hello</title>
</head>

<body>
    <h1>Hello, {{ name }}!</h1>
</body>

</html>

hello/app1/templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
    </body>
</html>

hello/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello World!</title>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                document.querySelector('select').onchange =  function() {
                    console.log('one time.');
                    document.querySelector('h1').style.color = this.value;
                }
            })
        </script>
    </head>
    <body>
        <h1 id="hello">Hello World!</h1>
        <select name="Black">
            <option value="black">Black</option>
            <option value="red">Red</option>
            <option value="blue">Blue</option>
            <option value="green">Green</option>
        </select>
    </body>
</html>

hello/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>New Year?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

hello/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Add Task</h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">New View</a>
{% endblock %}

hello/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% empty %}
                <li>No Task</li>
            {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

hello/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>